apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server
  labels:
    app: game-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
      - name: game-server
        image: gcr.io/qingyangc-sandbox/kubemmo/server
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: game-server
spec:
  selector:
    app: game-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
