apiVersion: apps/v1
kind: Deployment
metadata:
  name: player2
  labels:
    app: player2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player2
  template:
    metadata:
      labels:
        app: player2
    spec:
      containers:
      - name: player
        image: gcr.io/qingyangc-sandbox/kubemmo/player:random
        imagePullPolicy: Always
        env:
        - name: USERNAME
          value: "you"
