apiVersion: apps/v1
kind: Deployment
metadata:
  name: player
  labels:
    app: player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      labels:
        app: player
    spec:
      containers:
      - name: player
        image: gcr.io/qingyangc-sandbox/kubemmo/player:random
